name: ${pluginName}
main: com.github.civcraft.donum.Donum
author: Maxopoly
version: ${version}
depend: [CivModCore, NameLayer]
description: ${description}
api-version: ${api_version}
permissions:
  donum.op:
    default: op
